//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Account_management_system.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AMS_dbEntities : DbContext
    {
        public AMS_dbEntities()
            : base("name=AMS_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_admin> tbl_admin { get; set; }
        public virtual DbSet<tbl_customer> tbl_customer { get; set; }
        public virtual DbSet<tbl_Expense> tbl_Expense { get; set; }
        public virtual DbSet<tbl_expense_category> tbl_expense_category { get; set; }
        public virtual DbSet<tbl_extra_account> tbl_extra_account { get; set; }
        public virtual DbSet<tbl_income_category> tbl_income_category { get; set; }
        public virtual DbSet<tbl_land_account> tbl_land_account { get; set; }
        public virtual DbSet<tbl_notification> tbl_notification { get; set; }
        public virtual DbSet<tbl_notification_receiver> tbl_notification_receiver { get; set; }
        public virtual DbSet<tbl_parmision> tbl_parmision { get; set; }
        public virtual DbSet<tbl_role> tbl_role { get; set; }
        public virtual DbSet<tbl_salary_expense> tbl_salary_expense { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
        public virtual DbSet<tbl_login_registration> tbl_login_registration { get; set; }
    }
}
