//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Account_management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Expense
    {
        public int expense_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> expense_category { get; set; }
        public Nullable<int> expense_amount { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string year { get; set; }
        public string expense_discription { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> ex_category_id { get; set; }
    
        public virtual tbl_expense_category tbl_expense_category { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
