//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Account_management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_land_account
    {
        public int l_id { get; set; }
        public string recevier { get; set; }
        public Nullable<int> payment_process { get; set; }
        public string pay_order_no { get; set; }
        public Nullable<int> payment_type { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string year { get; set; }
        public string payment_discription { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> customer_id { get; set; }
    
        public virtual tbl_customer tbl_customer { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
