//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Account_management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_expense_category
    {
        public tbl_expense_category()
        {
            this.tbl_Expense = new HashSet<tbl_Expense>();
        }
    
        public int ex_category_id { get; set; }
        public string category_name { get; set; }
    
        public virtual ICollection<tbl_Expense> tbl_Expense { get; set; }
    }
}
