//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Account_management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_salary_expense
    {
        public int salary_expense_id { get; set; }
        public string employee_id { get; set; }
        public Nullable<int> salary_type { get; set; }
        public Nullable<int> salary_amount { get; set; }
        public string user_name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string year { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual tbl_user tbl_user { get; set; }
    }
}
