//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Account_management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_notification
    {
        public tbl_notification()
        {
            this.tbl_notification_receiver = new HashSet<tbl_notification_receiver>();
        }
    
        public int notification_id { get; set; }
        public string sender { get; set; }
        public string notification { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> category_id { get; set; }
    
        public virtual tbl_income_category tbl_income_category { get; set; }
        public virtual ICollection<tbl_notification_receiver> tbl_notification_receiver { get; set; }
    }
}
