//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Account_management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_admin
    {
        public int admin_id { get; set; }
        public string employeeid { get; set; }
        public string admin_name { get; set; }
        public string admin_email { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> admin_access { get; set; }
        public Nullable<int> admin_level { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual tbl_user tbl_user { get; set; }
    }
}
