//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Account_management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_extra_account
    {
        public int income_id { get; set; }
        public Nullable<int> payment_process { get; set; }
        public string pay_order_ddno { get; set; }
        public Nullable<int> incame_cetegory { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string year { get; set; }
        public Nullable<int> amount { get; set; }
        public string receiver_id { get; set; }
        public string payment_discription { get; set; }
        public Nullable<int> user_id { get; set; }
        public int category_id { get; set; }
    
        public virtual tbl_income_category tbl_income_category { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
