//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Account_management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_income_category
    {
        public tbl_income_category()
        {
            this.tbl_extra_account = new HashSet<tbl_extra_account>();
            this.tbl_notification = new HashSet<tbl_notification>();
        }
    
        public int category_id { get; set; }
        public string category_name { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual ICollection<tbl_extra_account> tbl_extra_account { get; set; }
        public virtual tbl_user tbl_user { get; set; }
        public virtual ICollection<tbl_notification> tbl_notification { get; set; }
    }
}
